# main text of home
name: Colin Adams
bio: Often sitting.

# Markdown renderer
markdown: kramdown

# twitter summary info
description:

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/cropped_rabi.png

# If you want to include your resume, set to true
# and specify source (external orn local).
resume: false
resume-external: false
resume-url:

url: https://cbadams2.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google:

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: # enter this from your disqus account
  categories: [] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
github: cbadams2
#linkedin:
#instructables:
#googlescholar: eGVw-FAAAAAJ&hl=en
#twitter:
# facebook:
# youtube:
# spotify:
# stackoverflow:
# medium:
# email:

authors:
    colin:
        name: Colin
        bio:
        external-image: false
        picture:
        twitter:

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: false

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: false

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com
